version: "3.9"
services:
  form-api:
    image: decodingtrustagent/google-form:api-latest
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: host
    restart: unless-stopped
    environment:
      - SCHEMA_PATH=/app/schemas/schema.json
      - ALLOW_ORIGINS=*
      - SCHEMA_INIT=/app/init/schema.json
      - GOOGLE_FORM_API_PORT=${GOOGLE_FORM_API_PORT:-8054}
    volumes:
      - form_data:/app/data

  form-ui:
    image: decodingtrustagent/google-form:ui-latest
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: host
    restart: unless-stopped
    environment:
      - VITE_API_BASE=/api
      - GOOGLE_FORM_UI_PORT=${GOOGLE_FORM_UI_PORT:-8055}
      - GOOGLE_FORM_API_PORT=${GOOGLE_FORM_API_PORT:-8054}
    depends_on:
      - form-api

volumes:
  form_data:
